#!/usr/bin/python3
'''check {fmt} consistency.

Check msgid and msgstr have the same {fmt}, which Python format and Lua-fmt can specify in replacement field.
'''
# Copyright © 2026 OOTA, Masato
# This program is published under MIT License.

import argparse
import pathlib
import string
import sys

import podict
import podict.dump

arg_parser = argparse.ArgumentParser()
arg_parser.add_argument('--preserve-path', action='store_true', help='Show the source filename preserved the path.')
arg_parser.add_argument('files', metavar='PO files', nargs='*', help='Input filenames, or stdin if a single "-" or nothing is specified.')
args = arg_parser.parse_args()

id_start = string.ascii_letters + '_'
id_continue = id_start + string.digits
def extract_args(text):
    '''Extract args in the replacement field.'''
    args = set()
    idx = 0
    while (idx := text.find('{', idx)) >= 0:
        e_idx = text.find('}', idx + 1)
        if e_idx < 0:
            break
        if e_idx > idx + 1:
            # Not Empty
            arg = text[idx+1:e_idx]
            if arg[0] in id_start:
                id = arg[0]
                for c in arg[1:]:
                    if c in id_continue:
                        id += c
                        continue
                    elif c == ':':
                        break
                    else:
                        id = None
                        break
                if id is not None:
                    args.add(id)
        idx = e_idx + 1
    return args

def check_a_file(f, filename, display_preserve_path):
    fname = filename if display_preserve_path else pathlib.Path(filename).name
    po_entries, _, error_messages = podict.parse(f)
    if len(error_messages) > 0:
        for err in error_messages:
            sys.stderr.write(f'{fname}:{err[0]},{err[1]}: {err[2]}.\n')
        sys.stderr.write('Stop reporting.\n')
        return 1
    else:
        for entry in po_entries.values():
            if 'fuzzy' in entry:
                continue
            msgid = entry['msgid']
            msgid_args = extract_args(msgid)
            msgid_plural_args = None
            if 'msgid_plural' in entry:
                msgid_plural = entry['msgid_plural']
                msgid_plural_args = extract_args(msgid_plural)
            for i, msgstr in enumerate(entry['msgstr']):
                if len(msgstr) == 0:
                    continue
                msgstr_args = extract_args(msgstr)
                unmatch_args = msgid_args ^ msgstr_args
                unmatch = False
                if len(unmatch_args) > 0:
                    if msgid_plural_args is None:
                        unmatch = True
                    else:
                        unmatch_plural_args = msgid_plural_args ^ msgstr_args
                        if len(unmatch_plural_args) > 0:
                            unmatch = True
                if unmatch:
                    print(f'{fname}:{entry["line"]}:{entry["column"]}: Unmatched arguments are found.')
                    print(f'  Unmatched argument(s): {unmatch_args}', end='')
                    if msgid_plural_args is not None and unmatch_args != unmatch_plural_args:
                        print(f' or {unmatch_plural_args}', end='')
                    print('')
                    joiner = '\n  '
                    d_msgid = podict.dump.to_quote_text(msgid, joiner)
                    d_msgstr = podict.dump.to_quote_text(msgstr, joiner)
                    print(f'  msgid: {d_msgid}')
                    if msgid_plural_args is not None:
                        d_msgid_plural = podict.dump.to_quote_text(msgid_plural, joiner)
                        print(f'  msgid_plural: {d_msgid_plural}')
                        print(f'  msgstr[{i}]: {d_msgstr}')
                    else:
                        print(f'  msgstr: {d_msgstr}')
        return 0


if len(args.files) == 0:
    filenames = ( '-', )
else:
    filenames = args.files
for filename in filenames:
    if filename == '-':
        exit_code = check_a_file(sys.stdin, 'stdin', False)
    else:
        with open(filename, 'r', encoding='utf-8') as f:
            exit_code = check_a_file(f, filename, args.preserve_path)
    if exit_code != 0:
        sys.exit(exit_code)
